### ISSUE TITLE
There is no STM32 pins definition.  It is still for Arduino UNO.  Where is cpu_map.h for STM32? 

### ISSUE THREAD

**Issue by dineshvyas** [mstrens/grbl_6axis_on_stm32#4]

**Comment by mstrens** [comment]
The config  files are here
https://github.com/mstrens/grbl_6axis_on_stm32/tree/master/6-AXIS-USBCNC-GRBL-master/inc

There are sections for STM32.

**Comment by dineshvyas** [comment]
Thanks, I figured it out. Created a new file stm32_cpu_map.h and included it in cpu_map.h. compiled and flashed with Stlink v2. But how to connect it to host program ie universal gcode sender?
USB doesn't work, FTDI doesn't work.

**Comment by dineshvyas** [comment]
Problem solved
