### ISSUE TITLE
Weird G0 Behaviour

### ISSUE THREAD

**Issue by e-zeki** [mstrens/grbl_6axis_on_stm32#7]
Hello again. 
I've build my machine it works great now. 
But a weird Feed rate error happens from time to time. 
When I start a file, some how it starts half of max speed for G0 commands for no apparent reason. and it works on normal speed for other commands in file. but every G0 is half of max speed. when I restart the file it goes as it should be. 
Why would this happen? I dont get any error or alarms. am I missing some sort of important message when this happens?

**Comment by mstrens** [comment]
Sorry but I have no idea why this happens.
Does it happens also if you reduce 
- the Feed rate of G0 in the GRBL parameter
- the number of steps/mm in GRBL parameter and set your drivers for using less microstreps
Perhaps you are just at the limit of the power of STM32 for generate fast step pulses.
Still I do not understand why it happens only from time to time.

**Comment by e-zeki** [comment]
I did change and reduced all parameters but still continues. it randomly does this when I start a new job. it does the job correctly %100 but sometimes at the beginning it reads exactly half of the max speed and it continues all the way with that speed.
I'll let you know if I can find the solution 
Cheers.

**Comment by mstrens** [comment]
Perhaps you can put an issue on this site
https://github.com/robomechs/6-AXIS-USBCNC-GRBL

I think my own version was a fork from this one and afterwards I fixed some bugs.

**Comment by e-zeki** [comment]
Yes I know your where your version came from. I also asked this in there but seems owner is stopped supporting the repo. weirdly enough: I assembled a new PCB but used same blue pill on it. It works now.  I don't really understand if it was an EMC, static charge, faulty component etc. why would only be making mistakes about Feed rate? how selective is it? After a new assembled pcb it works and haven't had a feed rate error since. Thanks again.
